### TES DATA

In [2]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import point

desa = gpd.read_file(
    r"../data/batas_wilayah/Batas_Wilayah_KelurahanDesa_10K_AR.shp", 
    where="WADMKK = 'Bandung'" 
)

print(f"Berhasil.....\nDitemukan {len(desa)} desa/kelurahan di Kabupaten Bandung.\nCRS Polygon:{desa.crs}")

Berhasil.....
Ditemukan 280 desa/kelurahan di Kabupaten Bandung.
CRS Polygon:EPSG:4326

In [3]:
# catatan. titik desa ada 280 titik desa di kab bandung CRS POLYGON adalah EPSD:4326 #

In [15]:
status = {"jumlah desa": f"{len(desa)}",
          "CRS Polygon": f"{desa.crs}"}

df = pd.DataFrame([status])
df

  jumlah desa CRS Polygon
0         280   EPSG:4326

In [16]:
df.to_csv("status_data.csv", index=False)

## EKSPERIMEN PEMBUATAN FUNCTION MULAI DARI BAWAH SINI
### FUNCTION PIP_EXPERIMENT():

#### 1. Load polygon dataset (desa/kelurahan)
#### 2. Ensure CRS consistency
#### 3. Load point dataset
#### 4. Perform point-in-polygon (point → desa)
#### 5. Attach administrative attributes (kecamatan)
#### 6. Export results (per kecamatan / per desa)

In [1]:
from src.pip_core import (
    load_polygon_admin,
    load_points_datasets,
    run_pip,
    export_by_kecamatan)

# load batas wilayah sebagai polygon

desa = load_polygon_admin(
    "../data/batas_wilayah/Batas_Wilayah_KelurahanDesa_10K_AR.shp",
    kabupaten='Bandung'
    )

In [2]:
help(load_points_datasets)

Help on function load_points_datasets in module src.pip_core:

load_points_datasets(
    csv_path: str,
    sep: str = ';',
    lon_col: str = 'longitude',
    lat_col: str = 'latitude',
    crs=None
) -> geopandas.geodataframe.GeoDataFrame

In [2]:
csv_path="../data/data_existing/DATA_BERSIH_RADIUS.csv"

points = load_points_datasets(
    csv_path=csv_path,
    sep=';',
    lon_col="longitude", 
    lat_col="latitude",
    crs=desa.crs)

In [3]:
points = points.drop(points['name'])
points.head()

KeyError: "[' (1300 VA)', ' 0011', ' 24-JUL-17 13:06:06', ' 00111', ' 2017-07-22 9:17:17AM', ' 13-OCT-15 9:25:09', ' 24-AUG-16 11:05:25', ' 02-JUN-03 16:37:17', ' 0013', ' 0014', ' 2018-02-06 9:40:08AM', ' 2018-01-26 11:21:02AM', ' 0019', ' 2018-09-03 2:15:54PM', ' 0021', ' 00210', ' 2017-07-22 9:18:28AM', ' 13-OCT-15 9:28:22', ' 24-AUG-16 11:07:59', ' 03-JUN-03 10:24:25', ' 0022', ' 0024', ' 0025', ' 2018-02-06 9:45:26AM', ' 0028', ' 24-JUL-17 13:06:44', ' 2018-09-03 2:17:11PM', ' 0031', ' 2017-07-22 9:20:00AM', ' 13-OCT-15 9:31:55', ' 03-JUN-03 10:34:00', ' 0032', ' 0034', ' 0035', ' 2018-02-06 9:46:16AM', ' 0038', ' 24-JUL-17 13:07:07', ' 0041', ' 00410', ' 2017-07-22 9:20:21AM', ' 24-AUG-16 11:15:00', ' 03-JUN-03 10:54:19', ' 0042', ' 0044', ' 0045', ' 2018-02-06 9:55:07AM', ' 0048', ' 0051', ' 2017-07-22 9:22:12AM', ' 2016-02-26 9:59:30AM', ' 24-AUG-16 11:24:47', ' 03-JUN-03 10:55:30', ' 0052', ' 0054', ' 0055', ' 2018-02-06 9:56:54AM', ' 0057', ' 0058', ' 2018-09-03 2:18:43PM', ' 0061', ' 2017-07-22 9:23:07AM', ' 13-OCT-15 9:47:12', ' 2016-02-26 10:01:58AM', ' 24-AUG-16 11:34:10', ' 03-JUN-03 10:55:47', ' 0062', ' 0064', ' 2018-02-06 9:58:25AM', ' 0067', ' 0068', ' 0071', ' 00710', ' 2017-07-22 9:24:00AM', ' 13-OCT-15 9:49:21', ' 24-AUG-16 11:46:41', ' 03-JUN-03 10:58:14', ' 0072', ' 0074', ' 0075', ' 2018-02-06 10:00:16AM', ' 0077', ' 0078', ' 2018-09-03 2:19:53PM', ' 0081', ' 00810', ' 2017-07-22 9:24:50AM', ' 13-OCT-15 9:51:35', ' 2016-02-26 10:57:56AM', ' 24-AUG-16 11:49:48', ' 03-JUN-03 13:05:52', ' 0082', ' 0084', ' 0085', ' 2018-02-06 10:15:21AM', ' 0087', ' 0088', ' 2018-09-17 9:54:53AM', ' 0091', ' 2017-07-22 9:25:59AM', ' 13-OCT-15 9:53:44', ' 2016-02-26 10:58:32AM', ' 24-AUG-16 11:51:51', ' 03-JUN-03 13:08:15', ' 2023-07-05 10:08:30AM', ' 0092', ' 0094', ' 0095', ' 0097', ' 0098', ' 2018-09-17 9:56:13AM', ' 0101', ' 2017-07-22 9:26:20AM', ' 13-OCT-15 9:57:44', ' 2016-02-26 10:59:17AM', ' 24-AUG-16 11:57:21', ' 03-JUN-03 13:08:52', ' 2023-07-05 10:09:04AM', ' 0103', ' 2018-02-06 10:18:43AM', ' 0106', ' 0107', ' 24-JUL-17 13:13:04', ' 0109', ' 0111', ' 2017-07-22 9:27:06AM', ' 13-OCT-15 9:59:05', ' 2016-02-26 11:00:12AM', ' 24-AUG-16 12:02:19', ' 03-JUN-03 13:09:26', ' 2023-07-05 10:09:23AM', ' 0113', ' 0114', ' 2018-02-06 10:20:14AM', ' 0116', ' 0117', ' 24-JUL-17 13:13:40', ' 0119', ' 0121', ' 01210', ' 2017-07-22 9:27:42AM', ' 2016-02-26 11:00:55AM', ' 24-AUG-16 12:05:05', ' 03-JUN-03 13:29:20', ' 2023-07-05 10:09:54AM', ' 0124', ' 2018-02-06 10:30:41AM', ' 0127', ' 0128', ' 0131', ' 01310', ' 13-OCT-15 10:23:27', ' 24-AUG-16 12:11:06', ' 03-JUN-03 13:29:56', ' 2023-07-05 10:10:30AM', ' 0132', ' 0134', ' 0135', ' 2018-02-06 10:31:42AM', ' 0137', ' 0138', ' 24-JUL-17 13:23:46', ' 0141', ' 01410', ' 2017-07-22 9:28:23AM', ' 13-OCT-15 10:25:30', ' 2016-02-26 11:02:34AM', ' 03-JUN-03 13:31:04', ' 2023-07-05 10:10:53AM', ' 0142', ' 0144', ' 0145', ' 0147', ' 0148', ' 24-JUL-17 13:25:31', ' 2018-09-17 9:57:45AM', ' 0151', ' 01510', ' 2017-07-22 9:30:16AM', ' 24-AUG-16 12:14:40', ' 03-JUN-03 13:31:33', ' 2023-07-05 10:11:28AM', ' 0154', ' 0155', ' 0158', ' 24-JUL-17 13:26:57', ' 2018-09-17 9:57:56AM', ' 0161', ' 01610', ' 2017-07-22 9:31:11AM', ' 24-AUG-16 12:19:29', ' 04-JUN-03 9:30:42', ' 2023-07-05 10:12:10AM', ' 0162', ' 0164', ' 0165', ' 0168', ' 24-JUL-17 13:27:53', ' 2018-09-17 9:58:28AM', ' 0171', ' 01710', ' 2017-07-22 9:32:40AM', ' 13-OCT-15 10:56:58', ' 2016-02-26 11:11:59AM', ' 24-AUG-16 12:24:30', ' 04-JUN-03 9:36:09', ' 2023-07-05 10:13:04AM', ' 0172', ' 0174', ' 0175', ' 0177', ' 0178', ' 24-JUL-17 13:30:41', ' 2018-09-17 9:59:02AM', ' 0181', ' 01810', ' 2017-07-22 9:34:02AM', ' 13-OCT-15 10:59:29', ' 2016-02-26 11:12:41AM', ' 04-JUN-03 9:44:11', ' 2023-07-05 10:13:36AM', ' 0182', ' 0184', ' 0185', ' 2018-04-10 9:08:44AM', ' 0187', ' 24-JUL-17 13:31:38', ' 0191', ' 01910', ' 2017-07-22 9:34:20AM', ' 12-JUL-17 10:20:37', ' 13-OCT-15 11:01:40', ' 2016-02-26 11:14:04AM', ' 24-AUG-16 12:29:30', ' 04-JUN-03 9:44:37', ' 2023-07-05 10:14:52AM', ' 0192', ' 0194', ' 0197', ' 0198', ' 24-JUL-17 13:32:37', ' 02.01.01.001', ' 02.01.01.002', ' 02.01.01.003', ' 02.01.01.004', ' 02.01.01.005', ' 02.01.01.006', ' 02.01.01.007', ' 02.01.01.008', ' 02.01.01.009', ' 02.01.02-001', ' 02.01.02-002', ' 02.01.02-003', ' 02.01.02-004', ' 02.01.02-005', ' 02.01.02-006', ' 02.01.02-007', ' 02.01.02-008', ' 02.01.02-009', ' 02.01.106.001', ' 02.01.106.002', ' 02.01.106.003', ' 02.01.106.004', ' 02.01.106.005', ' 02.01.106.006', ' 02.01.106.007', ' 02.01.110.001', ' 02.01.110.002', ' 02.01.110.003', ' 02.01.110.004', ' 02.01.110.005', ' 02.01.141.001', ' 02.01.141.002', ' 02.01.141.003', ' 02.01.141.004', ' 02.01.141.005', ' 02.01.141.006', ' 02.01.141.007', ' 02.01.149.002', ' 02.01.149.003', ' 02.01.149.004', ' 02.01.149.005', ' 02.01.149.006', ' 02.01.149.007', ' 02.01.149.008', ' 02.01.155.001', ' 02.01.155.002', ' 02.01.155.003', ' 02.01.155.005', ' 02.01.155.006', ' 02.01.157.001', ' 02.01.157.002', ' 02.01.157.003', ' 02.01.157.005', ' 02.01.157.007', ' 02.01.17.001', ' 02.01.17.003', ' 02.01.17.005', ' 02.01.17.006', ' 02.01.178.001', ' 02.01.178.002', ' 02.01.178.003', ' 02.01.178.004', ' 02.01.178.005', ' 02.01.178.006', ' 02.01.185.001', ' 02.01.185.002', ' 02.01.185.003', ' 02.01.185.004', ' 02.01.185.005', ' Yonif Linud 330 Kostrad', ' 02.01.185.007', ' 02.01.185.008', ' 02.01.185.009', ' 02.01.185.010', ' 02.01.23.001', ' 02.01.23.002', ' 02.01.23.003', ' 02.01.23.004', ' 02.01.23.005', ' 02.01.23.006', ' 02.01.23.007', ' 02.01.23.008', ' 02.01.23.009', ' 02.01.23.010', ' 02.01.29.001', ' 02.01.29.002', ' 02.01.29.003', ' 02.01.29.004', ' 02.01.29.005', ' 02.01.31.001', ' 02.01.31.001.2', ' 02.01.31.002', ' 02.01.31.002.2', ' 02.01.31.003', ' 02.01.31.003.2', ' 02.01.31.004.2', ' 02.01.31.005.2', ' 02.01.54.001', ' 02.01.54.002', ' 02.01.54.003', ' 02.01.54.004', ' 02.01.54.005', ' 02.01.54.006', ' 02.01.60.009', ' 02.01.60.010', ' 02.01.60.011', ' 02.01.60.012', ' 02.01.60.013', ' 02.01.70.001', ' 02.01.70.002', ' 02.01.70.003', ' 02.01.70.004', ' 02.01.70.005', ' 02.01.70.006', ' 02.01.70.007', ' 02.01.80.001', ' 02.01.80.002', ' 02.01.80.003', ' 02.01.80.004', ' 02.01.80.005', ' 02.01.80.006', ' 02.01.93.001', ' 02.01.93.002', ' 02.01.93.003', ' 02.01.93.004', ' 02.01.93.005', ' 02.01.93.006', ' 02.01.93.007', ' 02.01.94.001', ' 02.01.94.002', ' 02.01.94.003', ' 02.01.94.004', ' 02.01.94.005', ' 02.01.94.006', ' 02.01.94.007', ' 2018-09-17 10:00:34AM', ' 0201', ' 2017-07-22 9:34:56AM', ' 2016-02-26 11:14:52AM', ' 04-JUN-03 9:45:26', ' 2023-07-05 10:15:32AM', ' 0204', ' 0207', ' 0208', ' 24-JUL-17 13:34:22', ' 2018-09-17 10:01:11AM', ' 0211', ' 02110', ' 2017-07-22 9:35:49AM', ' 2016-02-26 11:19:46AM', ' 24-AUG-16 12:37:06', ' 04-JUN-03 10:18:02', ' 2023-07-05 10:15:59AM', ' 0214', ' 0217', ' 24-JUL-17 13:35:04', ' 2018-09-17 10:01:58AM', ' 0221', ' 02210', ' 2017-07-22 9:36:25AM', ' 2016-02-26 11:20:20AM', ' 24-AUG-16 12:39:41', ' 04-JUN-03 11:03:45', ' 2023-07-05 10:16:21AM', ' 0224', ' 0227', ' 0228', ' 24-JUL-17 13:37:08', ' 0231', ' 02310', ' 13-OCT-15 11:10:01', ' 2016-02-26 11:20:45AM', ' 24-AUG-16 12:44:43', ' 04-JUN-03 11:11:47', ' 2023-07-05 10:16:45AM', ' 0235', ' 2018-04-10 9:28:45AM', ' 0237', ' 0238', ' 2018-09-17 10:04:03AM', ' 0241', ' 02410', ' 2017-07-22 9:38:01AM', ' 13-OCT-15 11:11:30', ' 2016-02-26 11:21:24AM', ' 24-AUG-16 12:48:00', ' 04-JUN-03 11:45:27', ' 2023-07-05 10:16:58AM', ' 0245', ' 0247', ' 0248', ' 24-JUL-17 13:41:06', ' 2018-09-17 10:04:15AM', ' 0251', ' 02510', ' 2017-07-22 9:39:17AM', ' 13-OCT-15 11:13:07', ' 24-AUG-16 13:25:55', ' 04-JUN-03 11:54:08', ' 2023-07-05 10:18:12AM', ' 0254', ' 0255', ' 0257', ' 0258', ' 24-JUL-17 13:41:44', ' 2018-09-17 10:04:31AM', ' 0261', ' 02610', ' 2017-07-22 9:39:54AM', ' 2016-02-26 11:29:39AM', ' 24-AUG-16 13:27:56', ' 04-JUN-03 12:02:50', ' 2023-07-05 10:18:39AM', ' 0264', ' 0265', ' 0267', ' 24-JUL-17 13:42:34', ' 2018-09-17 10:06:44AM', ' 0271', ' 2017-07-22 9:40:30AM', ' 24-AUG-16 13:28:19', ' 04-JUN-03 12:29:24', ' 2023-07-05 10:19:40AM', ' 0274', ' 0275', ' 0277', ' 0278', ' 24-JUL-17 13:46:09', ' 02810', ' 2017-07-22 9:40:54AM', ' 13-OCT-15 11:28:37', ' 2016-02-26 11:33:04AM', ' 04-JUN-03 12:39:16', ' 2023-07-05 10:20:06AM', ' 0284', ' 0285', ' 2018-04-10 9:42:38AM', ' 0287', ' 0288', ' 24-JUL-17 13:50:54', ' 2018-09-17 10:07:06AM', ' 0291', ' 2017-07-22 9:41:25AM', ' 2016-02-26 11:33:22AM', ' 24-AUG-16 13:40:06', ' 04-JUN-03 12:41:50', ' 2023-07-05 10:21:28AM', ' 0294', ' 0295', ' 2018-04-10 9:43:32AM', ' 0297', ' 0298', ' 24-JUL-17 13:57:37', ' 2018-09-17 10:07:41AM', ' 03010', ' 2017-07-22 9:41:52AM', ' 2016-02-26 11:33:39AM', ' 04-JUN-03 12:46:28', ' 2023-07-05 10:21:55AM', ' 0304', ' 2018-04-10 9:44:42AM', ' 0307', ' 0308', ' 0311', ' 03110', ' 2017-07-22 9:42:31AM', ' 13-OCT-15 11:32:13', ' 24-AUG-16 13:51:16', ' 04-JUN-03 13:19:34', ' 2023-07-05 10:22:22AM', ' 0314', ' 0315', ' 0317', ' 24-JUL-17 14:00:22', ' 2018-09-17 10:08:02AM', ' 0321', ' 2017-07-22 9:43:25AM', ' 2016-03-02 2:53:39PM', ' 24-AUG-16 13:53:21', ' 04-JUN-03 13:20:16', ' 2023-07-05 10:22:42AM', ' 0324', ' 0325', ' 0327', ' 0328', ' 24-JUL-17 14:01:03', ' 2018-09-17 10:08:13AM', ' 0331', ' 03310', ' 2017-07-22 9:43:40AM', ' 2016-03-02 2:57:00PM', ' 24-AUG-16 13:58:54', ' 04-JUN-03 13:31:56', ' 2023-07-05 10:23:08AM', ' 0334', ' 0335', ' 2018-04-10 9:51:35AM', ' 0337', ' 0338', ' 24-JUL-17 14:01:42', ' 0341', ' 03410', ' 2017-07-22 9:44:00AM', ' 2016-03-02 2:58:07PM', ' 24-AUG-16 14:39:07', ' 04-JUN-03 13:32:59', ' 2023-07-05 10:25:38AM', ' 0344', ' 0345', ' 0348', ' 24-JUL-17 14:02:14', ' 2018-09-17 10:10:12AM', ' 0351', ' 03510', ' 2017-07-22 9:44:39AM', ' 04-JUN-03 13:41:01', ' 2023-07-05 10:26:20AM', ' 0354', ' 0355', ' 0357', ' 0358', ' 24-JUL-17 14:03:13', ' 2018-09-17 10:10:24AM', ' 0361', ' 03610', ' 2017-07-22 9:45:18AM', ' 13-OCT-15 11:38:20', ' 2016-03-02 3:02:52PM', ' 04-JUN-03 15:00:46', ' 2023-07-05 10:40:34AM', ' 0364', ' 0365', ' 2018-04-10 10:43:04AM', ' 0367', ' 0368', ' 2018-09-17 10:10:47AM', ' 0371', ' 03710', ' 2017-07-22 9:46:28AM', ' 13-OCT-15 11:39:43', ' 2016-03-02 3:03:14PM', ' 24-AUG-16 14:46:32', ' 04-JUN-03 15:11:04', ' 2023-07-05 10:41:35AM', ' 0374', ' 0377', ' 0378', ' 2018-09-17 10:11:31AM', ' 0381', ' 2017-07-22 9:46:47AM', ' 2016-03-02 3:04:37PM', ' 24-AUG-16 14:49:22', ' 04-JUN-03 16:23:05', ' 2023-07-05 10:42:18AM', ' 0384', ' 2018-04-10 10:44:07AM', ' 0387', ' 0388', ' 2018-09-17 10:11:39AM', ' 0391', ' 03910', ' 2017-07-22 9:46:58AM', ' 13-OCT-15 11:42:25', ' 2016-03-02 3:06:13PM', ' 24-AUG-16 14:51:02', ' 04-JUN-03 16:25:21', ' 2023-07-05 10:43:24AM', ' 0394', ' 0398', ' 2018-09-17 10:11:48AM', ' 0401', ' 2017-07-22 9:47:15AM', ' 2016-03-02 3:07:01PM', ' 24-AUG-16 14:54:46', ' 05-JUN-03 12:22:02', ' 2023-07-05 10:43:56AM', ' 0404', ' 0408', ' 24-JUL-17 14:06:40', ' 2018-09-17 10:11:59AM', ' 0411', ' 2017-07-22 9:47:29AM', ' 13-OCT-15 11:50:06', ' 2016-03-02 3:08:15PM', ' 24-AUG-16 14:56:41', ' 05-JUN-03 12:23:00', ' 2023-07-05 10:44:39AM', ' ELEVATION: 1500-1600 METER', ' 0414', ' 2018-04-10 10:54:19AM', ' 0417', ' 0418', ' 2018-09-17 10:12:11AM', ' 0421', ' 04210', ' 2017-07-22 9:47:42AM', ' 13-OCT-15 12:05:31', ' 2016-03-02 3:09:16PM', ' 05-JUN-03 12:23:38', ' 0422', ' 0424', ' 0428', ' 2018-09-17 10:12:23AM', ' 0431', ' 04310', ' 2017-07-22 9:48:46AM', ' 13-OCT-15 12:11:12', ' 2016-03-02 3:11:13PM', ' 05-JUN-03 12:48:48', ' 2023-07-05 10:48:20AM', ' 0432', ' 0434', ' 0437', ' 0438', ' 24-JUL-17 14:33:20', ' 2018-09-17 10:13:48AM', ' 0441', ' 04410', ' 2017-07-22 9:49:18AM', ' 13-OCT-15 12:13:36', ' 24-AUG-16 15:04:04', ' 05-JUN-03 13:01:42', ' 2023-07-05 10:49:01AM', ' 0442', ' 0444', ' 0447', ' 0448', ' 24-JUL-17 14:34:05', ' 2018-09-17 10:14:01AM', ' 0451', ' 04510', ' 2017-07-22 9:49:31AM', ' 13-OCT-15 12:14:41', ' 24-AUG-16 15:07:01', ' 05-JUN-03 13:22:31', ' 2023-07-05 10:49:35AM', ' 0452', ' 0454', ' 0458', ' 24-JUL-17 15:12:54', ' 2018-09-17 10:14:16AM', ' 04610', ' 2017-07-22 9:50:12AM', ' 13-OCT-15 12:15:52', ' 24-AUG-16 15:08:45', ' 05-JUN-03 13:23:00', ' 2023-07-05 10:50:09AM', ' 0462', ' 0464', ' 24-JUL-17 15:13:51', ' 0471', ' 2017-07-22 9:50:56AM', ' 13-OCT-15 12:45:52', ' 2016-03-02 3:22:53PM', ' 24-AUG-16 15:10:48', ' 05-JUN-03 13:23:57', ' 2023-07-05 10:50:40AM', ' 0472', ' 0474', ' 0475', ' 2018-04-16 7:05:05PM', ' 0478', ' 24-JUL-17 15:15:20', ' 24-JUL-17 15:16:19', ' 04811', ' 2017-07-22 9:51:20AM', ' 13-OCT-15 13:00:07', ' 2016-03-02 3:23:41PM', ' 24-AUG-16 15:14:30', ' 05-JUN-03 14:16:06', ' 2023-07-05 10:52:02AM', ' 0482', ' 0484', ' 0485', ' 2018-05-30 11:46:12PM', ' 0488', ' 0489', ' 2018-09-17 10:15:18AM', ' 0491', ' 24-JUL-17 15:17:29', ' 04911', ' 2017-07-22 9:51:45AM', ' 2016-03-02 3:24:18PM', ' 24-AUG-16 15:16:57', ' 05-JUN-03 14:16:43', ' 2023-07-05 10:52:23AM', ' 0492', ' 0499', ' 2018-09-17 10:15:34AM', ' 0501', ' 05010', ' 2017-07-22 9:52:04AM', ' 13-OCT-15 13:08:50', ' 2016-03-02 3:24:59PM', ' 05-JUN-03 14:18:35', ' 2023-07-05 10:52:47AM', ' 0502', ' 2018-06-26 11:52:06AM', ' 0507', ' 0508', ' 24-JUL-17 15:18:17', ' 2018-09-17 10:15:43AM', ' 0511', ' 2017-07-22 9:52:26AM', ' 2016-03-02 3:26:54PM', ' 24-AUG-16 15:21:52', ' 05-JUN-03 14:29:09', ' 2023-07-05 10:54:29AM', ' 0512', ' 0514', ' 0515', ' 2018-06-26 12:00:11PM', ' 0517', ' 0518', ' 24-JUL-17 15:19:03', ' 2018-09-17 10:15:57AM', ' 0521', ' 05210', ' 2017-07-22 9:52:37AM', ' 13-OCT-15 13:26:42', ' 2016-03-02 3:27:54PM', ' 24-AUG-16 15:25:41', ' 05-JUN-03 14:29:41', ' 2023-07-05 10:55:00AM', ' 0522', ' 0524', ' 2018-06-26 12:01:45PM', ' 0527', ' 0528', ' 24-JUL-17 15:19:48', ' 2018-09-17 10:16:12AM', ' 0531', ' 05310', ' 2017-07-22 9:52:51AM', ' 2016-03-02 3:28:49PM', ' 10-JUN-03 9:40:06', ' 2023-07-05 10:55:22AM', ' 0532', ' 0534', ' 2018-06-26 12:02:28PM', ' 0537', ' 0538', ' 24-JUL-17 15:20:29', ' 0541', ' 2017-07-22 9:55:55AM', ' 13-OCT-15 13:28:37', ' 2016-03-02 3:29:27PM', ' 24-AUG-16 15:30:15', ' 10-JUN-03 9:50:33', ' 2023-07-05 10:56:24AM', ' 0542', ' 2018-06-26 12:04:06PM', ' 0547', ' 0548', ' 24-JUL-17 15:21:10', ' 2018-09-17 10:16:53AM', ' 0551', ' 2017-07-22 10:04:20AM', ' 13-OCT-15 13:29:24', ' 2016-03-02 3:32:15PM', ' 24-AUG-16 15:41:27', ' 10-JUN-03 9:51:30', ' 2023-07-05 10:56:46AM', ' 0552', ' 0554', ' 2018-06-26 12:17:34PM', ' 0558', ' 24-JUL-17 15:22:03', ' 2018-09-17 10:17:01AM', ' 0561', ' 05610', ' 2017-07-22 10:04:52AM', ' 13-OCT-15 13:31:07', ' 2016-03-02 3:33:18PM', ' 24-AUG-16 15:44:44', ' 10-JUN-03 10:32:13', ' 2023-07-05 10:57:08AM', ' 0562', ' 0564', ' 2018-06-26 12:18:21PM', ' 0567', ' 0568', ' 24-JUL-17 15:23:08', ' 2018-09-17 10:17:49AM', ' 0571', ' 05710', ' 2017-07-22 10:06:48AM', ' 13-OCT-15 13:34:57', ' 2016-03-02 3:33:52PM', ' 24-AUG-16 15:47:21', ' 10-JUN-03 10:33:03', ' 2023-07-05 10:57:51AM', ' 0572', ' 0574', ' 2018-06-26 12:19:10PM', ' 0577', ' 0578', ' 24-JUL-17 15:25:33', ' 2018-09-17 10:18:09AM', ' 0581', ' 05810', ' 2017-07-22 10:07:32AM', ' 13-OCT-15 13:36:10', ' 2016-03-02 3:34:24PM', ' 10-JUN-03 10:34:00', ' 2023-07-05 10:58:19AM', ' 0582', ' 2018-06-26 12:20:00PM', ' 0587', ' 0588', ' 24-JUL-17 15:26:34', ' 2018-09-17 10:18:17AM', ' 0591', ' 05910', ' 2017-07-22 10:08:15AM', ' 2016-03-02 3:34:49PM', ' 24-AUG-16 15:58:20', ' 10-JUN-03 11:33:41', ' 2023-07-05 10:58:38AM', ' 0592', ' 0594', ' 2018-06-26 12:20:35PM', ' 0598', ' 24-JUL-17 15:27:30', ' 2018-09-17 10:18:28AM', ' 0601', ' 2017-07-22 10:09:21AM', ' 11-JUL-17 11:39:06', ' 13-OCT-15 13:39:35', ' 2016-03-02 3:35:20PM', ' 24-AUG-16 15:59:40', ' 10-JUN-03 11:38:30', ' 2023-07-05 11:17:52AM', ' 0602', ' 2018-06-26 12:22:51PM', ' 0607', ' 0608', ' 24-JUL-17 15:28:19', ' 2018-09-17 10:24:05AM', ' 0611', ' 06110', ' 2017-07-22 10:10:11AM', ' 11-JUL-17 11:41:13', ' 13-OCT-15 13:42:04', ' 2016-03-02 3:36:02PM', ' 24-AUG-16 16:04:09', ' 10-JUN-03 11:50:53', ' 2023-07-05 11:19:28AM', ' 0612', ' 0614', ' 2018-06-26 12:23:31PM', ' 0617', ' 0618', ' 24-JUL-17 15:29:11', ' 2018-09-17 10:24:16AM', ' 06210', ' 2017-07-22 10:12:02AM', ' 11-JUL-17 11:42:15', ' 13-OCT-15 13:42:43', ' 2016-03-02 3:36:50PM', ' 24-AUG-16 16:08:13', ' 10-JUN-03 12:00:52', ' 0622', ' 0624', ' 0625', ' 2018-06-26 1:50:35PM', ' 0627', ' 0628', ' 24-JUL-17 15:29:56', ' 2018-09-17 10:24:28AM', ' 0631', ' 06310', ' 2017-07-22 10:14:25AM', ' 11-JUL-17 11:43:16', ' 13-OCT-15 13:44:21', ' 2016-03-02 3:37:17PM', ' 24-AUG-16 16:10:16', ' 10-JUN-03 13:00:42', ' 2023-07-05 11:30:09AM', ' 0632', ' 0634', ' 0635', ' 2018-06-26 1:51:16PM', ' 0637', ' 0638', ' 24-JUL-17 15:30:40', ' 2018-09-17 10:24:40AM', ' 0641', ' 06410', ' 2017-07-22 10:15:19AM', ' 11-JUL-17 11:44:55', ' 13-OCT-15 13:45:27', ' 2016-03-02 3:38:51PM', ' 24-AUG-16 16:12:22', ' 10-JUN-03 13:01:26', ' 2023-07-05 11:33:02AM', ' 0642', ' 0644', ' 2018-06-26 1:55:13PM', ' 0647', ' 0648', ' 24-JUL-17 15:31:17', ' 2018-09-17 10:25:22AM', ' 0651', ' 06510', ' 2017-07-22 10:15:44AM', ' 13-OCT-15 13:46:24', ' 2016-03-02 3:39:40PM', ' 10-JUN-03 14:17:41', ' 2023-07-05 11:33:33AM', ' 0652', ' 0654', ' 0655', ' 2018-06-26 1:55:51PM', ' 0657', ' 0658', ' 24-JUL-17 15:32:40', ' 2018-09-17 10:25:37AM', ' 0661', ' 06610', ' 2017-07-22 10:16:21AM', ' 2016-03-02 3:40:31PM', ' 10-JUN-03 14:18:17', ' 2023-07-05 11:34:47AM', ' 0662', ' 0664', ' 2018-06-26 2:00:54PM', ' 0667', ' 0668', ' 24-JUL-17 15:33:17', ' 2018-09-17 10:26:27AM', ' 0671', ' 06710', ' 2017-07-22 10:16:33AM', ' 13-OCT-15 13:57:38', ' 2016-03-02 3:41:11PM', ' 25-AUG-16 10:53:14', ' 12-JUN-03 10:22:14', ' 2023-07-05 11:36:52AM', ' 0672', ' 0674', ' 2018-06-26 2:25:24PM', ' 0677', ' 0678', ' 24-JUL-17 15:34:15', ' 2018-09-17 10:26:40AM', ' 0681', ' 06810', ' 2017-07-22 10:17:35AM', ' 13-OCT-15 13:58:38', ' 2016-03-02 3:41:52PM', ' 12-JUN-03 10:34:25', ' 2023-07-05 11:39:38AM', ' 0682', ' 0684', ' 0687', ' 24-JUL-17 15:35:08', ' 2018-09-17 10:26:48AM', ' 0691', ' 06910', ' 2017-07-22 10:18:05AM', ' 13-OCT-15 13:59:18', ' 2016-03-02 3:42:43PM', ' 12-JUN-03 11:00:28', ' 2023-07-05 11:42:01AM', ' 0692', ' 0694', ' 0697', ' 0698', ' 24-JUL-17 15:36:16', ' 07-1146', ' 07-1147', ' 07-1148', ' 07-1172', ' 07-1173', ' 07-1174', ' 07-1175', ' 07-1176', ' 07-1182', ' 07-1183', ' 07-1184', ' 07-1185', ' 07-1186', ' 07-1187', ' 2018-09-17 10:27:04AM', ' 2017-07-22 10:18:21AM', ' 13-OCT-15 13:59:46', ' 2016-03-02 3:43:45PM', ' 25-AUG-16 11:05:20', ' 12-JUN-03 11:34:08', ' 2023-07-05 11:42:54AM', ' 0702', ' 0704', ' 2018-06-26 2:45:03PM', ' 0707', ' 0708', ' 24-JUL-17 15:36:55', ' 2018-09-17 10:27:20AM', ' 0711', ' 07110', ' 2017-07-22 10:18:31AM', ' 17-OCT-15 10:58:47', ' 2016-03-02 3:44:37PM', ' 25-AUG-16 11:08:56', ' 12-JUN-03 11:41:56', ' 2023-07-05 11:47:31AM', ' 0712', ' 0714', ' 2018-06-26 3:04:55PM', ' 0717', ' 0718', ' 24-JUL-17 15:48:12', ' 2018-09-17 10:27:30AM', ' 0721', ' 07210', ' 2017-07-22 10:18:59AM', ' 17-OCT-15 11:00:26', ' 25-AUG-16 11:12:03', ' 12-JUN-03 11:42:10', ' 2023-07-05 11:48:20AM', ' 0722', ' 0724', ' 0725', ' 2018-06-26 3:11:09PM', ' 0727', ' 0728', ' 24-JUL-17 15:55:58', ' 2018-09-17 10:27:39AM', ' 0731', ' 07310', ' 2017-07-22 10:19:12AM', ' 17-OCT-15 11:02:30', ' 25-AUG-16 11:13:34', ' 12-JUN-03 12:17:48', ' 2023-07-05 11:51:44AM', ' 0732', ' 0734', ' 0735', ' 2018-06-26 3:15:54PM', ' 0737', ' 0738', ' 24-JUL-17 16:09:15', ' 2018-09-17 10:28:59AM', ' 0741', ' 07410', ' 2017-07-22 10:20:40AM', ' 17-OCT-15 11:03:35', ' 2016-03-02 3:48:41PM', ' 25-AUG-16 11:15:54', ' 2016-08-23 10:20:19AM', ' 12-JUN-03 12:18:31', ' 2023-07-10 9:18:17AM', ' 0742', ' 0744', ' 0745', ' 2018-06-26 3:16:35PM', ' 0748', ' 24-JUL-17 16:12:48', ' 2018-09-17 10:30:28AM', ' 0751', ' 07510', ' 2017-07-22 10:21:23AM', ' 17-OCT-15 11:07:41', ' 2016-03-02 3:50:23PM', ' 25-AUG-16 11:17:55', ' 12-JUN-03 12:18:56', ' 2023-07-10 9:18:45AM', ' 0752', ' 0754', ' 0755', ' 2018-06-26 3:19:45PM', ' 0758', ' 24-JUL-17 16:15:27', ' 2018-09-17 10:30:46AM', ' 0761', ' 07610', ' 2017-07-22 10:22:20AM', ' 17-OCT-15 11:09:42', ' 2016-03-02 3:51:23PM', ' 25-AUG-16 11:21:30', ' 2016-08-23 10

In [4]:
pip_results = run_pip(
    points_gdf=points,
    polygon_gdf=desa)

pip_results.head()

,latitude,longitude,name,geometry,index_right,WADMKC,WADMKD
0,-7.03350,107.70821,(1300 VA),POINT (107.70821 -7.0335),158,Ciparay,Sarimahi
1,-7.02030,107.52908,0011,POINT (107.52908 -7.0203),249,Soreang,Pamekaran
2,-6.99598,107.74772,24-JUL-17 13:06:06,POINT (107.74772 -6.99598),200,Rancaekek,Sukamanah
3,-7.00942,107.61916,00111,POINT (107.61916 -7.00942),182,Baleendah,Baleendah
4,-6.99180,107.53228,2017-07-22 9:17:17AM,POINT (107.53228 -6.9918),205,Kutawaringin,Cibodas

In [5]:
pip_results.value_counts()

latitude  longitude  name                   geometry                    index_right  WADMKC     WADMKD
-7.28772  107.67594  2018-06-26 12:23:31PM  POINT (107.67594 -7.28772)  0            Kertasari  Neglawangi    1
-7.28739  107.67631  2018-06-26 12:22:51PM  POINT (107.67631 -7.28739)  0            Kertasari  Neglawangi    1
-7.28709  107.67662  5514                   POINT (107.67662 -7.28709)  0            Kertasari  Neglawangi    1
-7.28655  107.67709  5505                   POINT (107.67709 -7.28655)  0            Kertasari  Neglawangi    1
-7.28623  107.67724  5495                   POINT (107.67724 -7.28623)  0            Kertasari  Neglawangi    1
                                                                                                             ..
-6.84549  107.65261  11-JUL-17 16:50:49     POINT (107.65261 -6.84549)  265          Cimenyan   Ciburial      1
-6.84513  107.65338  11-JUL-17 16:51:12     POINT (107.65338 -6.84513)  265          Cimenyan   Ciburial      1
-6.84495  107.65440  11-JUL-17 16:53:45     POINT (107.6544 -6.84495)   265          Cimenyan   Ciburial      1
-6.84494  107.65427  11-JUL-17 16:51:53     POINT (107.65427 -6.84494)  265          Cimenyan   Ciburial      1
-6.84480  107.65456  10087                  POINT (107.65456 -6.8448)   265          Cimenyan   Ciburial      1
Name: count, Length: 21883, dtype: int64

In [6]:
export_by_kecamatan(
    pip_results,
    "../data/output/kecamatan"
)