In [188]:
#from src.gps_convert import parse_coord

#ngetes = parse_coord("S6.96580 E107.75553")

#print(f"ini koordinat hasil tes: {ngetes} \n.....\nSelanjutnya ditindaklanjuti.")

EKSEKUSI DARI BAWAH SINI!

In [189]:
import pandas as pd
from src.gps_convert import parse_coord

df = pd.read_csv(r"../data/data_existing/olahdata.csv")


df

                koordinat
0   S6 52.837 E107 39.581
1   S6 52.819 E107 39.578
2   S6 52.802 E107 39.566
3   S6 52.816 E107 39.595
4   S6 52.833 E107 39.598
5   S6 52.850 E107 39.599
6   S6 52.850 E107 39.612
7   S6 52.847 E107 39.627
8   S6 52.821 E107 39.621
9   S6 52.831 E107 39.618
10  S6 52.829 E107 39.637
11  S6 52.836 E107 39.651
12  S6 52.818 E107 39.655
13  S6 52.809 E107 39.644
14  S6 52.799 E107 39.619
15  S6 52.787 E107 39.626
16  S6 52.793 E107 39.640
17  S6 52.798 E107 39.607

In [190]:
coords = []

for koor in df["koordinat"]:
    lat, lon = parse_coord(koor)
    coords.append(f"{lat:.6f}, {lon:.6f}")


df['koordinat']=coords
df

                koordinat
0   -6.880617, 107.659683
1   -6.880317, 107.659633
2   -6.880033, 107.659433
3   -6.880267, 107.659917
4   -6.880550, 107.659967
5   -6.880833, 107.659983
6   -6.880833, 107.660200
7   -6.880783, 107.660450
8   -6.880350, 107.660350
9   -6.880517, 107.660300
10  -6.880483, 107.660617
11  -6.880600, 107.660850
12  -6.880300, 107.660917
13  -6.880150, 107.660733
14  -6.879983, 107.660317
15  -6.879783, 107.660433
16  -6.879883, 107.660667
17  -6.879967, 107.660117

In [191]:
df.to_csv("output.csv", index=False)
print("selesai!\nperiksa file output.csv")

selesai!
periksa file output.csv